export class CreateUserDto {
    created_date: Date
    first_name: string
    last_name: string
    email: string
    password: string
    mobile: number
    Personal_summary: string
    jobtittle: string
    employer: string
    location: string
    from: Date
    to: Date
    description: string
    education_provider: string
    qualification: string
    year_completed: number
    valid_in_NZ?: string
    education_description: string
    licence_name: string
    issuing_authority: string
    issue_date: Date
    expiry_date: Date
    validinNZ?: string
    certificate_name: string
    certifications_issuing_authority: string
    certifications_issue_date: Date
    certifications_expiry_date: Date
    certifications_validinNZ?: string
    Certifications_description: string
    skills: string
    availability: string
    full_time: string
    part_time: string
    causal: string
    contract: string
    freelance: string
    temporary: string
    preferred_locations: string
    preferred_job_category: Date
    expected_rate_per_hour$: number
    show_profile: string
    visa_type: string
    visa_expiry_date: Date
    upload_cover_letter: string
    uploadcv: string

}